### ISSUE TITLE
Issue with evaluating MeSH

### ISSUE THREAD

**Issue by shruti-singh** [allenai/scirepeval#34]
Hello

First of all, thank you for creating this exhaustive dataset! 

I am trying to reproduce SPECTER evaluation, starting with the MeSH task. Due to limited computational resources, I set `batch_size=16` instead of the default `32`:

```
from scirepeval import SciRepEval
from evaluation.encoders import Model

model = Model(variant="default", base_checkpoint="allenai/specter")
evaluator = SciRepEval(tasks_config="scirepeval_tasks.jsonl", task_list=["MeSH"], batch_size=16)
evaluator.evaluate(model, "scirepeval_results.json")
```

Later, it tries to fit an SVM to the dataset with `cv=3` and the size of `x_train=13`, I get the error that `n_splits=3 cannot be greater than the number of members in each class` because MeSH dataset has 30 descriptors. Could you please suggest how to work around this?

Thank you!

cc: @amanpreet692

**Comment by amanpreet692** [comment]
Hello! thanks for using our framework :)
Just checking in if you were able to resolve the issue?

**Comment by shruti-singh** [comment]
> 

Thanks for checking. It turned out to be an issue of not having enough memory and was resolved by further reducing the batch_size. Thanks!
