### ISSUE TITLE
NonMatchingChecksumError for the search benchmark

### ISSUE THREAD

**Issue by shruti-singh** [allenai/scirepeval#35]
Hi

I am running into the following error while loading the train split of the search dataset:

```
datasets.utils.info_utils.NonMatchingChecksumError: Checksums didn't match for dataset source files:
['https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/search/train.jsonl', 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/search/val.jsonl', 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/search/meta.jsonl']
```

Could you please help?

**Comment by amanpreet692** [comment]
Hello, 
Sorry for the late reply must have missed this!
We uploaded a new version of the search data set after removing some unwanted columns. This must have messed up the HuggingFace checksum metadata for the dataset. We have updated the metadata now.
Could you please try deleting the search dataset from HuggingFace cache and re-trying. It should work now.

**Comment by shruti-singh** [comment]
Thanks, it works now!

**Comment by Siri101** [comment]
hi,
I am evaluating OpenAI embeddings and there raises a NonMatchingChecksumError as follows:

datasets.utils.info_utils.NonMatchingChecksumError: Checksums didn't match for dataset source files:
['https://ai2-s2-research-public.s3.us-west 2.amazonaws.com/scirepeval/test/feeds/feeds_1/meta.jsonl'].

Could you please check it?

**Comment by amanpreet692** [comment]
Hello, this should be fixed now!
Also, please raise a new issue if there are any other issues.

**Comment by lpassarella** [comment]
Hi,

I had a similar issue and switched to datasets==2.5.2, however I got another error:

`  File "/home/8lp/anaconda3/envs/s2_fos/lib/python3.8/site-packages/datasets/features/features.py", line 1284, in generate_from_dict
    return Sequence(feature=generate_from_dict(obj["feature"]), length=obj["length"])
KeyError: 'length'`

Do you know how to fix this?

**Comment by amanpreet692** [comment]
Hello, 
We haven't seen this error before, please open a new issue with more details from the stack trace and we can take a look.
