### ISSUE TITLE
S2AND Evaluation: Missing param --emb_suffix

### ISSUE THREAD

**Issue by shruti-singh** [allenai/scirepeval#38]
Hi 

The [benchmarking readme](https://github.com/allenai/scirepeval/blob/main/BENCHMARKING.md) mentions the following command to run the S2AND evaluation:
```cd S2AND; python scripts/custom_block_transfer_experiment_seed_paper.py --custom_block_path <data>/blocks --experiment_name mini_customblock_phantasm_v1 --exclude_medline --emb_suffix _<suffix>.pkl```

While evaluating it, I run into the following error:
```custom_block_transfer_experiment_seed_paper.py: error: unrecognized arguments: --emb_suffix```

It seems like the `custom_block_transfer_experiment_seed_paper.py` in [S2AND repo](https://github.com/allenai/S2AND/blob/main/scripts/custom_block_transfer_experiment_seed_paper.py) doesn't contain the `emb_suffix` parameter. Am I looking at the correct code version?

cc: @amanpreet692

**Comment by amanpreet692** [comment]
Hello,
Thanks for pointing this out! We were using a modified script to evaluate embeddings from multiple models.
The change has been merged to S2AND now. So it should work with the `--emb_suffix` param now.

**Comment by shruti-singh** [comment]
Thanks, it works now!
