### ISSUE TITLE
openai dependency not listed in requirements

### ISSUE THREAD

**Issue by JohnGiorgi** [allenai/scirepeval#39]
The `openai` python library is imported by scirepeval ([here](https://github.com/allenai/scirepeval/blob/6bac48a151ac9a4f5bf05c092c73ade4cea7f9ad/evaluation/gpt3_encoder.py)) but not listed in the `requirements.txt`, so you get a `ModuleNotFoundError` when trying to run `scirepeval.py`, for example. Seems like its not required unless a user is evaluating openai embeddings, so might be worth wrapping the `import openai` statement in a try/except or something.

**Comment by amanpreet692** [comment]
wooo...Thanks John! I'll take care of this

**Comment by amanpreet692** [comment]
It should work now! I'll add steps to ReadME as well for evaluating Open AI embeddings

**Comment by JohnGiorgi** [comment]
Cool, thanks :)
