### ISSUE TITLE
Issues with examples/retrieval.py

### ISSUE THREAD

**Issue by shauryr** [allenai/scirepeval#42]
Thank you for building this awesome dataset. 

I wanted to ask if you have shared the weights mentioned in the following line -

https://github.com/allenai/scirepeval/blob/8f00aa9871bb0b41c29e60f3dafcff9043b9799c/examples/retrieval.py#L17

I want to reproduce the results for [QRY] task. 
I saw this - https://huggingface.co/allenai/scirepeval_adapters_qry But I am not sure how to use this for the example shared. 

Thanks in advance.

**Comment by sergeyf** [comment]
Hey Shaurya,

You want to reproduce the results on the exact datasets in SciRepEval or use for your own purposes?

If the latter, just go to https://huggingface.co/allenai/specter_plus_plus and follow the directions

Specter++ with QRY to encode the search query and then with PRX to encode the result papers is what we did for search.

**Comment by shauryr** [comment]
Hey Sergey,

Thanks for the response.
I actually want to do both. We are augmenting some more data at our end and
benchmarking a new model on scirepeval specifically the search task.

I will use specter++ for the latter! thank you

**Comment by sergeyf** [comment]
@amanpreet692 can comment about how to do a single task.

**Comment by amanpreet692** [comment]
Hey Shaurya, 

- So to replicate our results on search and similar tasks, plz use the adhoc_query and proximity adapter models [here](https://huggingface.co/models?search=allenai/spp), and follow the Filter Tasks instructions at the end of [BENCHMARKING.md](https://github.com/allenai/scirepeval/blob/main/BENCHMARKING.md).  Replace the adapters in `adapters_dict` , `base_checkpoint=allenai/specter_plus_plus` and `task_list` with the required task name from [scirepeval_tasks.jsonl](https://github.com/allenai/scirepeval/blob/main/scirepeval_tasks.jsonl).

- To benchmark a new model, replace the model definition in the previous step

- To evaluate on a custom task, you can follow the steps [here](https://github.com/allenai/scirepeval/blob/main/evaluation/EVALUATION.md#custom-tasks). The `SciRepEval` class internally calls the methods given in the example script above, but is config driven so you can just define the new task in config file and run the evaluations.

Hope this helps!

**Comment by shauryr** [comment]
Hi Amanpreet,

Thank you for your reply and insights. This does help.
Here is what I am doing for just the search task -

```
adapters_dict = {
    "[QRY]": "allenai/scirepeval_adapters_qry",
    "[PRX]": "allenai/scirepeval_adapters_prx",
}
model = Model(
    variant="adapters",
    base_checkpoint="allenai/specter_plus_plus",
    adapters_load_from=adapters_dict,
    all_tasks=["[QRY]", "[PRX]"],
)

# Choose the task names from scirepeval_tasks.jsonl
evaluator = SciRepEval(task_list=["Search"])
evaluator.evaluate(model, "scirepeval_results.json")
```
So this should work right? If yes please close the issue.
I tried it on a smaller GPU and it runs half way until CUDA gives memory errors. 
I am still waiting for my turn to run this on a big GPU. 

Thank you for the help :) also scirepeval is pretty awesome.

**Comment by amanpreet692** [comment]
Yip!! That's it :) 
If you are running into OOM issues, you can provide the `batch_size` argument to `SciRepEval` which has a default value of 32.
Thanks again...happy you find the work useful!
I'll close this issue, plz open a new one if you run into something else.
