### ISSUE TITLE
checksum errors on feed* subsets

### ISSUE THREAD

**Issue by kwchurch** [allenai/scirepeval#43]
It looks like someone updated the files one AWS in a way that breaks huggingface datasets

ds=load_dataset('allenai/scirepeval', 'feeds_1')
Downloading and preparing dataset scirepeval/feeds_1 (download: 6.57 MiB, generated: 6.19 MiB, post-processed: Unknown size, total: 12.75 MiB) to /home/k.church/.cache/huggingface/datasets/allenai___scirepeval/feeds_1/1\
.1.0/05b6b341c1750891a5539df5b3eb892babd18e8f299bfaba4735b87e20f6cf83...
{'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/feeds/feeds_1/meta.jsonl'}
Downloading data files: 100% 1/1 [00:00<00:00, 313.69it/s]
Extracting data files: 100% 1/1 [00:00<00:00, 103.28it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/k.church/venv/gft/lib/python3.8/site-packages/datasets/load.py", line 1731, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/k.church/venv/gft/lib/python3.8/site-packages/datasets/builder.py", line 640, in download_and_prepare
    self._download_and_prepare(
  File "/home/k.church/venv/gft/lib/python3.8/site-packages/datasets/builder.py", line 1158, in _download_and_prepare
    super()._download_and_prepare(dl_manager, verify_infos, check_duplicate_keys=verify_infos)
  File "/home/k.church/venv/gft/lib/python3.8/site-packages/datasets/builder.py", line 711, in _download_and_prepare
    verify_checksums(
  File "/home/k.church/venv/gft/lib/python3.8/site-packages/datasets/utils/info_utils.py", line 40, in verify_checksums
    raise NonMatchingChecksumError(error_msg + str(bad_urls))
datasets.utils.info_utils.NonMatchingChecksumError: Checksums didn't match for dataset source files:
['https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/feeds/feeds_1/meta.jsonl']

I'm finding similar errors for 'feeds_1'  and 'feeds_m' and 'feeds_title'

I tried deleting my cached files, but the same error came back again

The other subsets load without error.

head feed*txt
==> feeds_1.txt <==
dataset: allenai/scirepeval     dataset: allenai/scirepeval     downloads: 491  likes: 1        
Downloading and preparing dataset scirepeval/feeds_1 (download: 6.57 MiB, generated: 6.19 MiB, post-processed: Unknown size, total: 12.75 MiB) to /home/k.church/.cache/huggingface/datasets/allenai___scirepeval/feeds_1/1\
.1.0/05b6b341c1750891a5539df5b3eb892babd18e8f299bfaba4735b87e20f6cf83...
{'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/feeds/feeds_1/meta.jsonl'}
***ERROR***
model: None
data: H:allenai/scirepeval,feeds_1
eqn: None
splits: train
split: train
task: None

==> feeds_m.txt <==
dataset: allenai/scirepeval     dataset: allenai/scirepeval     downloads: 491  likes: 1        
Downloading and preparing dataset scirepeval/feeds_m (download: 141.83 MiB, generated: 128.96 MiB, post-processed: Unknown size, total: 270.78 MiB) to /home/k.church/.cache/huggingface/datasets/allenai___scirepeval/feed\
s_m/1.1.0/05b6b341c1750891a5539df5b3eb892babd18e8f299bfaba4735b87e20f6cf83...
{'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/feeds/feeds_m/meta.jsonl'}
***ERROR***
model: None
data: H:allenai/scirepeval,feeds_m
eqn: None
splits: train
split: train
task: None

==> feeds_title.txt <==
dataset: allenai/scirepeval     dataset: allenai/scirepeval     downloads: 491  likes: 1        
Downloading and preparing dataset scirepeval/feeds_title (download: 5.91 MiB, generated: 5.65 MiB, post-processed: Unknown size, total: 11.56 MiB) to /home/k.church/.cache/huggingface/datasets/allenai___scirepeval/feeds\
_title/1.1.0/05b6b341c1750891a5539df5b3eb892babd18e8f299bfaba4735b87e20f6cf83...
{'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/feeds/feeds_title/meta.jsonl'}
***ERROR***
model: None
data: H:allenai/scirepeval,feeds_title
eqn: None
splits: train
split: train
task: None

**Comment by sergeyf** [comment]
Apologies, @amanpreet692 will be fixing this today.

**Comment by amanpreet692** [comment]
Hello this should work now! The metadata on hugging face has been updated.
As a side note, if this occurs again please raise an issue and meanwhile you should be able to bypass the checksum verification with the ``ignore_verifications=True`` argument in ``load_dataset()``

**Comment by Siri101** [comment]
It seems that it occurs again and I have deleted the dataset in cache.

datasets.utils.info_utils.NonMatchingChecksumError: Checksums didn't match for dataset source files:
['https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/feeds/feeds_m/meta.jsonl']

**Comment by amanpreet692** [comment]
Apologies for this, it seems that the metadata for `feeds_m` and `feeds_title` was not correctly re-generated as I had not cleared my cache. An updated version of the metadata has now been pushed to Hugging Face. It should work now if you give it a try.

**Comment by kwchurch** [comment]
feed_1, feed_m and feeds_title are now working

thx

unfortunately, there is a checksum error with search

dataset: allenai/scirepeval     dataset: allenai/scirepeval     downloads:
622  likes: 1

Downloading and preparing dataset scirepeval/search (download: 9.01 GiB,
generated: 7.47 GiB, post-processed: Unknown size, total: 16.49 GiB) to
/home/k.church/.cache/huggingface/datasets/allenai___scirepeval/search/1.1.0/05b6b341c1750891a5539df5b3eb89\

2babd18e8f299bfaba4735b87e20f6cf83...

{'train': '
https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/search/train.jsonl',
'val': '
https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/search/val.jsonl',
'test': 'https://ai2-s2-research-public.s3.\

us-west-2.amazonaws.com/scirepeval/test/search/meta.jsonl'}

***ERROR***

model: None

data: H:allenai/scirepeval,search

eqn: None

splits: train

split: train

task: None

error: (<class 'datasets.utils.info_utils.NonMatchingChecksumError'>,
NonMatchingChecksumError("Checksums didn't match for dataset source
files:\n['
https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/search/train.jsonl',
'https:/\

/
ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/search/val.jsonl',
'
https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/search/meta.jsonl']"),
<traceback object at 0x2b7963150640>)

**Comment by amanpreet692** [comment]
All the configs for all the datasets have been updated and tested. It should work now hopefully!
