### ISSUE TITLE
ValueError when running benchmark

### ISSUE THREAD

**Issue by lpassarella** [allenai/scirepeval#46]
I am trying to run the simple example in the benchmark readme.

I am running
`python3 scirepeval.py -m allenai/specter`
but get the following error:
`ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.`

Unsure how to solve this

**Comment by amanpreet692** [comment]
Hello,
Did you also get a log indicating that GPUs are not available:
```
INFO:evaluation.evaluator:Generating embeddings... this might take a while
  0%|                                              | 0/343 [00:00<?, ?it/s]

No CUDA GPUs are available
```

The utility first uses the model to generate vector representations for the data and GPUs are required for good performance there.
Please let us know if this answers your query else please provide more logging context which would be helpful to solve this.
Thanks

**Comment by Siri101** [comment]
Hello, I also get the error when evaluating the OpenAI embeddings on SciDoc_MeSH dataset.
Moreover, I didn't get the log about GPU device.

`Traceback (most recent call last):
  File "scirepeval.py", line 148, in <module>
    evaluator.evaluate(model, args.output)
  File "scirepeval.py", line 106, in evaluate
    results = evaluator.evaluate(embeddings)
  File "/public/home/wangsj/scirepeval/evaluation/evaluator.py", line 101, in evaluate
    preds = eval_fn(x_train, x_test, y_train)
  File "/public/home/wangsj/scirepeval/evaluation/evaluator.py", line 132, in classify
    svm.fit(x_train, y_train)
  File "/home1/wangsj/.conda/envs/scirepeval/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 875, in fit
    self._run_search(evaluate_candidates)
  File "/home1/wangsj/.conda/envs/scirepeval/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 1379, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home1/wangsj/.conda/envs/scirepeval/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 835, in evaluate_candidates
    enumerate(candidate_params), enumerate(cv.split(X, y, groups))
  File "/home1/wangsj/.conda/envs/scirepeval/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 755, in split
    y = check_array(y, input_name="y", ensure_2d=False, dtype=None)
  File "/home1/wangsj/.conda/envs/scirepeval/lib/python3.8/site-packages/sklearn/utils/validation.py", line 909, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.`

**Comment by amanpreet692** [comment]
Hello,
To generate the OpenAI embeddings, you need to have an openai api key which will be used to connect to the OpenAI servers and generate the document embeddings for SciRepEval data.
Once you have the api key, you can set it as the environment variable:
```bash
export OPENAI_API_KEY=<open ai api key>
```
You might have seen something like following in the logs:
```
INFO:evaluation.evaluator:Generating embeddings... this might take a while
  0%|                                                                                                                                                                      | 0/343 [00:00<?, ?it/s]
No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://onboard.openai.com for details, or email support@openai.com if you have any questions.
INFO:evaluation.embeddings_generator:Generated 0 embeddings
```
And the openai mode doesn't use GPU because we connect to the open ai api to generate the embeddings.

Having said that, the issue for both OP and you is the same, just two different routes. If there are no embeddings, this would raise an error as  the embeddings are the inputs used for evaluating the data.

**Comment by lpassarella** [comment]
Thank you, I was able to run it :)
