### ISSUE TITLE
Issue when running training

### ISSUE THREAD

**Issue by lpassarella** [allenai/scirepeval#47]
I am tyring to run the training code:
`python3 pl_training.py --gpu 2 --tasks-config sample_data/tasks_config.json bert-base-uncased fos`

But I keep getting the following error:

> `python3 pl_training.py --gpu 2 --tasks-config sample_data/tasks_config.json bert-base-uncased fos
> Global seed set to 42
> dict_keys(['cite_pred', 'year_pred', 'mesh', 'fos', 'search', 's2and', 'cite_context', 'specter'])
> Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight']
> - This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> /home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:446: LightningDeprecationWarning: Setting `Trainer(gpus=2)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=2)` instead.
>   rank_zero_deprecation(
> Using 16bit native Automatic Mixed Precision (AMP)
> GPU available: True (cuda), used: True
> TPU available: False, using: 0 TPU cores
> IPU available: False, using: 0 IPUs
> HPU available: False, using: 0 HPUs
> `Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
> Global seed set to 42
> Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
> Global seed set to 42
> dict_keys(['cite_pred', 'year_pred', 'mesh', 'fos', 'search', 's2and', 'cite_context', 'specter'])
> Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight']
> - This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Global seed set to 42
> Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
> 2023-05-05 12:55:09 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 1
> 2023-05-05 12:55:09 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 0
> 2023-05-05 12:55:09 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
> ----------------------------------------------------------------------------------------------------
> distributed_backend=nccl
> All distributed processes registered. Starting with 2 processes
> ----------------------------------------------------------------------------------------------------
> 
> 2023-05-05 12:55:09 | INFO | torch.distributed.distributed_c10d | Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
> {'train': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/cite_count/train.jsonl', 'val': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/cite_count/val.jsonl', 'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/cite_count/meta.jsonl'}
> {'train': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/cite_count/train.jsonl', 'val': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/cite_count/val.jsonl', 'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/cite_count/meta.jsonl'}
> {'train': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/pub_year/train.jsonl', 'val': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/pub_year/val.jsonl', 'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/pub_year/meta.jsonl'}
> {'train': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/pub_year/train.jsonl', 'val': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/pub_year/val.jsonl', 'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/pub_year/meta.jsonl'}
> {'train': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/mesh_descriptors/train.jsonl', 'val': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/mesh_descriptors/val.jsonl', 'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/mesh_descriptors/meta.jsonl'}
> {'train': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/mesh_descriptors/train.jsonl', 'val': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/train/mesh_descriptors/val.jsonl', 'test': 'https://ai2-s2-research-public.s3.us-west-2.amazonaws.com/scirepeval/test/mesh_descriptors/meta.jsonl'}
> Traceback (most recent call last):
>   File "/home/8lp/scirepeval/training/pl_training.py", line 326, in <module>
>     trainer.fit(model)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
>     self._call_and_handle_interrupt(
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
>     results = self._run(model, ckpt_path=self.ckpt_path)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1107, in _run
>     self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1451, in _call_setup_hook
>     self._call_lightning_module_hook("setup", stage=fn)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1552, in _call_lightning_module_hook
>     output = fn(*args, **kwargs)
>   File "/home/8lp/scirepeval/training/pl_training.py", line 238, in setup
>     self.load_data("train")
>   File "/home/8lp/scirepeval/training/pl_training.py", line 216, in load_data
>     data = datasets.load_dataset(**data_src[0], split=data_src[1],streaming=True)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/load.py", line 1670, in load_dataset
>     builder_instance = load_dataset_builder(
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/load.py", line 1473, in load_dataset_builder
>     builder_instance: DatasetBuilder = builder_cls(
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/builder.py", line 1285, in __init__
>     super().__init__(*args, **kwargs)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/builder.py", line 347, in __init__
>     self.info = DatasetInfo.from_directory(self._cache_dir)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/info.py", line 284, in from_directory
>     return cls.from_dict(dataset_info_dict)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/info.py", line 289, in from_dict
>     return cls(**{k: v for k, v in dataset_info_dict.items() if k in field_names})
>   File "<string>", line 20, in __init__
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/info.py", line 145, in __post_init__
>     self.features = Features.from_dict(self.features)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/features/features.py", line 1597, in from_dict
>     obj = generate_from_dict(dic)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/features/features.py", line 1280, in generate_from_dict
>     return {key: generate_from_dict(value) for key, value in obj.items()}
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/features/features.py", line 1280, in <dictcomp>
>     return {key: generate_from_dict(value) for key, value in obj.items()}
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/features/features.py", line 1284, in generate_from_dict
>     return Sequence(feature=generate_from_dict(obj["feature"]), length=obj["length"])
> KeyError: 'length'
> /home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py:428: UserWarning: Error handling mechanism for deadlock detection is uninitialized. Skipping check.
>   rank_zero_warn("Error handling mechanism for deadlock detection is uninitialized. Skipping check.")
> Traceback (most recent call last):
>   File "pl_training.py", line 326, in <module>
>     trainer.fit(model)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
>     self._call_and_handle_interrupt(
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
>     return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
>     return function(*args, **kwargs)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
>     results = self._run(model, ckpt_path=self.ckpt_path)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1107, in _run
>     self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1451, in _call_setup_hook
>     self._call_lightning_module_hook("setup", stage=fn)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1552, in _call_lightning_module_hook
>     output = fn(*args, **kwargs)
>   File "pl_training.py", line 238, in setup
>     self.load_data("train")
>   File "pl_training.py", line 216, in load_data
>     data = datasets.load_dataset(**data_src[0], split=data_src[1],streaming=True)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/load.py", line 1670, in load_dataset
>     builder_instance = load_dataset_builder(
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/load.py", line 1473, in load_dataset_builder
>     builder_instance: DatasetBuilder = builder_cls(
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/builder.py", line 1285, in __init__
>     super().__init__(*args, **kwargs)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/builder.py", line 347, in __init__
>     self.info = DatasetInfo.from_directory(self._cache_dir)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/info.py", line 284, in from_directory
>     return cls.from_dict(dataset_info_dict)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/info.py", line 289, in from_dict
>     return cls(**{k: v for k, v in dataset_info_dict.items() if k in field_names})
>   File "<string>", line 20, in __init__
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/info.py", line 145, in __post_init__
>     self.features = Features.from_dict(self.features)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/features/features.py", line 1597, in from_dict
>     obj = generate_from_dict(dic)
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/features/features.py", line 1280, in generate_from_dict
>     return {key: generate_from_dict(value) for key, value in obj.items()}
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/features/features.py", line 1280, in <dictcomp>
>     return {key: generate_from_dict(value) for key, value in obj.items()}
>   File "/home/8lp/anaconda3/envs/scirepeval/lib/python3.8/site-packages/datasets/features/features.py", line 1284, in generate_from_dict
>     return Sequence(feature=generate_from_dict(obj["feature"]), length=obj["length"])
> KeyError: 'length'`

Any idea on how to solve this? I thought it could be an error with datasets or pytorch lightning but I have the correct versions loaded

**Comment by amanpreet692** [comment]
Hello,
I setup a fresh local copy of the repo and ran your command but unfortunately was not able to replicate the issue. Since the issue seems to be coming from the datasets library, maybe it's worth trying to load just the dataset in a notebook to see if you get the same error?

```python
import datasets
#training/validation/eval metadata
dataset = datasets.load_dataset("allenai/scirepeval", "mesh_descriptors")
```
