### ISSUE TITLE
Configure benchmark for SciNCL Adapters + MTL CTRL

### ISSUE THREAD

**Issue by sa-aguilarv** [allenai/scirepeval#50]
Hello! 
I'd like to run the benchmark for all tasks with SciNCL Adapters + MTL CTRL as the model, yet I'm unsure about the setup. Could you please give me some guidance?
Thank you in advance for your assistance

**Comment by amanpreet692** [comment]
Hello, that is ensemble setup where embeddings are generated using both the MTL CTRL and Adapters method.
You can find more info about evaluating this setup [here](https://github.com/allenai/scirepeval/blob/main/evaluation/EVALUATION.md#mean-pool-ensemble)

**Comment by sa-aguilarv** [comment]
It worked, thank you!
