### ISSUE TITLE
Configure S2AND task for ensemble setups: SciNCL + MTL CTRL + Adapters, and SciNCL + Adapters 

### ISSUE THREAD

**Issue by sa-aguilarv** [allenai/scirepeval#52]
Hello. I have questions regarding the S2AND task configuration for ensemble setups.

(1) To my understanding, this is for SciNCL. Is that correct? 
`python s2and_embeddings.py --model "malteos/scincl" --adapters-chkpt '{"[CLF]": "allenai/scirepeval_adapters_clf", "[QRY]": "allenai/scirepeval_adapters_qry", "[RGN]": "allenai/scirepeval_adapters_rgn", "[PRX]": "allenai/scirepeval_adapters_prx"}' --data-dir "s2and" --suffix "s2and-scincl"`
Is having the --adapters--chkpt argument a requirement to run this evaluation?
(2) How can we run the S2AND task evaluation for these ensemble setups: SciNCL + MTL CTRL + Adapters and SciNCL + Adapters? 

Thank you in advance for your assistance

**Comment by amanpreet692** [comment]
Hello,
1) If you want to run it only for SciNCL, you can discard the ``--adapters-chkpt` argument``
2) To run it for SciNCL + Adapters please add ``--mtype adapters `` and ``--adapters-chkpt`` args to your command.
Once the embeddings are generated, run the eval as per [here](https://github.com/allenai/scirepeval/blob/84d5671ae0ad2959119533b9d5df750814e048ac/BENCHMARKING.md#s2and-evaluation).

3) For SciNCL + MTL CTRL + Adapters,  Create a list of Models as in this [example](https://github.com/allenai/scirepeval/blob/84d5671ae0ad2959119533b9d5df750814e048ac/evaluation/EVALUATION.md#mean-pool-ensemble), and then create and then pass the s2and data_dir along with the model list as below to generate the embeddings:
```python
    evaluator = S2ANDEvaluator(data_dir, model_list)
    evaluator.generate_embeddings(suffix)

**Comment by sa-aguilarv** [comment]
It worked, thanks!
